from sqlalchemy.orm import Session

from app.models.game import EmotionConcept, Game, GameContent


GAME_RECOGNIZE_EMOTION = "3bcb2108-721c-4a15-a585-31f3084ed000"
GAME_FACE_ASSEMBLY = "33ecafaa-ec7e-40d2-9c67-ed0a29ac0051"
GAME_EMOTION_MATCH = "08bbffbf-d147-4556-bccb-b7621cafbf15"
GAME_DETECTIVE = "aacaf79e-e15e-42a9-a3d1-a522720d919b"
GAME_CV_STORY = "e05909f3-3dee-42a6-9a75-fd985b1bdf47"
GAME_CV_REQUEST = "61f5e09e-eefa-44c1-86e1-87dfceac3b8e"


GAMES = [
    {
        "game_id": GAME_RECOGNIZE_EMOTION,
        "game_type": "click_game",
        "name": "Chiếc hộp cảm xúc",
        "level": 8,
        "difficulty_level": "normal",
        "max_errors": 3,
        "level_threshold": 70,
        "time_limit": None,
    },
    {
        "game_id": GAME_FACE_ASSEMBLY,
        "game_type": "click_game",
        "name": "Xưởng lắp ghép",
        "level": 8,
        "difficulty_level": "normal",
        "max_errors": 3,
        "level_threshold": 70,
        "time_limit": None,
    },
    {
        "game_id": GAME_EMOTION_MATCH,
        "game_type": "click_game",
        "name": "Cảm xúc đúng chỗ",
        "level": 8,
        "difficulty_level": "normal",
        "max_errors": 3,
        "level_threshold": 75,
        "time_limit": None,
    },
    {
        "game_id": GAME_DETECTIVE,
        "game_type": "click_game",
        "name": "Thám tử cảm xúc",
        "level": 8,
        "difficulty_level": "normal",
        "max_errors": 3,
        "level_threshold": 75,
        "time_limit": None,
    },
    {
        "game_id": GAME_CV_STORY,
        "game_type": "camera_game",
        "name": "Câu chuyện khuôn mặt",
        "level": 5,
        "difficulty_level": "normal",
        "max_errors": 2,
        "level_threshold": 40,
        "time_limit": 30,
    },
    {
        "game_id": GAME_CV_REQUEST,
        "game_type": "camera_game",
        "name": "Thử thách cảm xúc",
        "level": 6,
        "difficulty_level": "normal",
        "max_errors": 2,
        "level_threshold": 40,
        "time_limit": 20,
    },
]


EMOTION_CONCEPTS = [
    {
        "concept_id": "concept-happy",
        "emotion": "happy",
        "level": 1,
        "title": "Vui vẻ",
        "video_path": "/fe/assets/videos/concepts/vui.mp4",
        "image_path": "/fe/assets/images/concepts/vui.jpg",
        "audio_path": "/fe/assets/audio/vui.mp3",
        "description": "Vui khi được khen, được nhận quà hoặc chơi cùng bạn bè.",
    },
    {
        "concept_id": "concept-sad",
        "emotion": "sad",
        "level": 1,
        "title": "Buồn bã",
        "video_path": "/fe/assets/videos/concepts/buon.mp4",
        "image_path": "/fe/assets/images/concepts/buon.jpg",
        "audio_path": None,
        "description": "Buồn khi mất đồ, bị mắng hoặc phải xa người thân.",
    },
    {
        "concept_id": "concept-angry",
        "emotion": "angry",
        "level": 1,
        "title": "Tức giận",
        "video_path": "/fe/assets/videos/concepts/tuc.mp4",
        "image_path": "/fe/assets/images/concepts/tuc.jpg",
        "audio_path": None,
        "description": "Tức giận khi bị lấy đồ hoặc bị đối xử không công bằng.",
    },
    {
        "concept_id": "concept-fear",
        "emotion": "fear",
        "level": 1,
        "title": "Sợ hãi",
        "video_path": None,
        "image_path": "/fe/assets/images/concepts/so.jpg",
        "audio_path": "/fe/assets/audio/so.mp3",
        "description": "Sợ khi nghe tiếng to, gặp điều lạ hoặc cảm thấy không an toàn.",
    },
    {
        "concept_id": "concept-surprise",
        "emotion": "surprise",
        "level": 1,
        "title": "Ngạc nhiên",
        "video_path": "/fe/assets/videos/concepts/ngac.mp4",
        "image_path": "/fe/assets/images/concepts/ngac.jpg",
        "audio_path": None,
        "description": "Ngạc nhiên khi có điều bất ngờ xảy ra.",
    },
    {
        "concept_id": "concept-disgust",
        "emotion": "disgust",
        "level": 1,
        "title": "Ghê tởm",
        "video_path": None,
        "image_path": "/fe/assets/images/concepts/ghe.jpg",
        "audio_path": None,
        "description": "Ghê tởm khi ngửi mùi hôi hoặc thấy thứ bẩn.",
    },
]


CV_STORY_CONTENT = [
    {
        "content_id": "cv-story-happy-1",
        "game_id": GAME_CV_STORY,
        "level": 1,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ được cô giáo khen vì giúp bạn nhặt đồ. Bạn ấy đang cảm thấy thế nào?",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Khi được khen hoặc làm điều tốt, khuôn mặt thường rạng rỡ và mỉm cười.",
    },
    {
        "content_id": "cv-story-sad-1",
        "game_id": GAME_CV_STORY,
        "level": 1,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ làm rơi cây kem yêu thích xuống đất. Khuôn mặt bạn ấy sẽ như thế nào?",
        "correct_answer": "sad",
        "emotion": "sad",
        "explanation": "Khi mất món đồ yêu thích, khuôn mặt có thể trầm xuống và khóe miệng hạ thấp.",
    },
    {
        "content_id": "cv-story-l1-surprise-1",
        "game_id": GAME_CV_STORY,
        "level": 1,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ mở hộp quà và thấy món đồ chơi mình mong muốn từ lâu. Khuôn mặt bạn ấy sẽ ra sao?",
        "correct_answer": "surprise",
        "emotion": "surprise",
        "explanation": "Khi gặp điều bất ngờ, mắt thường mở to và miệng hơi mở.",
    },
    {
        "content_id": "cv-story-l1-angry-1",
        "game_id": GAME_CV_STORY,
        "level": 1,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Một bạn giật đồ chơi khỏi tay bạn nhỏ mà không xin phép. Khuôn mặt bạn nhỏ có thể như thế nào?",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Khi bị đối xử không công bằng, lông mày có thể nhíu lại và mặt nghiêm hơn.",
    },
    {
        "content_id": "cv-story-l1-fear-1",
        "game_id": GAME_CV_STORY,
        "level": 1,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ nghe tiếng sấm rất to khi đang ở nhà. Bạn ấy có thể biểu hiện khuôn mặt ra sao?",
        "correct_answer": "fear",
        "emotion": "fear",
        "explanation": "Khi gặp âm thanh lớn bất ngờ, mắt có thể mở to và khuôn mặt căng hơn.",
    },
    {
        "content_id": "cv-story-angry-2",
        "game_id": GAME_CV_STORY,
        "level": 2,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ xếp tháp rất lâu nhưng em bé chạy tới làm đổ hết. Bạn ấy có thể biểu hiện ra sao?",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Khi công sức bị phá hỏng, khuôn mặt có thể nhíu mày và môi mím lại.",
    },
    {
        "content_id": "cv-story-l2-happy-1",
        "game_id": GAME_CV_STORY,
        "level": 2,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ được bố mẹ cho đi công viên sau một tuần cố gắng học tập. Bạn ấy sẽ thể hiện nét mặt gì?",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Khi mong muốn được đáp ứng, khuôn mặt thường sáng lên và cười tự nhiên.",
    },
    {
        "content_id": "cv-story-l2-disgust-1",
        "game_id": GAME_CV_STORY,
        "level": 2,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ ngửi thấy mùi thức ăn bị hỏng trong bếp. Khuôn mặt bạn ấy có thể thay đổi thế nào?",
        "correct_answer": "disgust",
        "emotion": "disgust",
        "explanation": "Khi gặp mùi khó chịu, mũi có thể nhăn lại và mặt hơi cau.",
    },
    {
        "content_id": "cv-story-l2-sad-1",
        "game_id": GAME_CV_STORY,
        "level": 2,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn thân chuyển sang lớp khác nên bạn nhỏ không còn được ngồi cạnh nữa. Khuôn mặt bạn ấy sẽ thế nào?",
        "correct_answer": "sad",
        "emotion": "sad",
        "explanation": "Khi phải xa người thân quen, ánh mắt có thể buồn và khuôn mặt trầm xuống.",
    },
    {
        "content_id": "cv-story-l2-surprise-1",
        "game_id": GAME_CV_STORY,
        "level": 2,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Cô giáo bất ngờ gọi tên bạn nhỏ lên nhận phần thưởng trước cả lớp. Bạn ấy sẽ phản ứng ra sao?",
        "correct_answer": "surprise",
        "emotion": "surprise",
        "explanation": "Khi điều bất ngờ xảy ra, lông mày có thể nâng lên và mắt mở to.",
    },
    {
        "content_id": "cv-story-l3-fear-1",
        "game_id": GAME_CV_STORY,
        "level": 3,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ đi lạc mẹ trong siêu thị đông người. Theo con, khuôn mặt bạn ấy lúc đó sẽ thế nào?",
        "correct_answer": "fear",
        "emotion": "fear",
        "explanation": "Khi không thấy người thân ở nơi đông người, khuôn mặt có thể căng thẳng và lo lắng.",
    },
    {
        "content_id": "cv-story-l3-happy-1",
        "game_id": GAME_CV_STORY,
        "level": 3,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ hoàn thành bức tranh và được cả nhà vỗ tay khen ngợi. Bạn ấy có thể biểu hiện ra sao?",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Khi tự hào và vui, nụ cười thường xuất hiện rõ trên khuôn mặt.",
    },
    {
        "content_id": "cv-story-l3-disgust-1",
        "game_id": GAME_CV_STORY,
        "level": 3,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ nhìn thấy chiếc bánh sinh nhật được giấu phía sau cánh cửa. Khuôn mặt sẽ thay đổi ra sao?",
        "correct_answer": "surprise",
        "emotion": "surprise",
        "explanation": "Khi thấy điều không ngờ tới, khuôn mặt có thể mở to mắt và miệng hơi há.",
    },
    {
        "content_id": "cv-story-l3-angry-1",
        "game_id": GAME_CV_STORY,
        "level": 3,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ đang xếp hàng nhưng có người chen lên trước. Khuôn mặt bạn ấy có thể ra sao?",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Khi thấy việc không công bằng, khuôn mặt có thể nghiêm và lông mày nhíu lại.",
    },
    {
        "content_id": "cv-story-l3-sad-1",
        "game_id": GAME_CV_STORY,
        "level": 3,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Con thú bông yêu thích của bạn nhỏ bị rách. Bạn ấy nhìn món đồ và im lặng. Khuôn mặt có thể thế nào?",
        "correct_answer": "sad",
        "emotion": "sad",
        "explanation": "Khi món đồ yêu thích bị hỏng, khuôn mặt thường trầm và ánh mắt buồn.",
    },
    {
        "content_id": "cv-story-l4-disgust-1",
        "game_id": GAME_CV_STORY,
        "level": 4,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ thử một món ăn có mùi vị lạ và muốn quay mặt đi. Khuôn mặt bạn ấy đang thể hiện điều gì?",
        "correct_answer": "disgust",
        "emotion": "disgust",
        "explanation": "Khi gặp vị hoặc mùi khó chịu, mũi thường nhăn và mặt hơi cau.",
    },
    {
        "content_id": "cv-story-l4-fear-1",
        "game_id": GAME_CV_STORY,
        "level": 4,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ chuẩn bị lên sân khấu lần đầu, tay nắm chặt áo và nhìn quanh. Khuôn mặt có thể ra sao?",
        "correct_answer": "fear",
        "emotion": "fear",
        "explanation": "Khi hồi hộp hoặc lo, khuôn mặt có thể căng và mắt mở to hơn.",
    },
    {
        "content_id": "cv-story-l4-happy-1",
        "game_id": GAME_CV_STORY,
        "level": 4,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ thấy người bạn lâu ngày gặp lại đang chạy tới ôm mình. Khuôn mặt bạn ấy có thể như thế nào?",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Khi gặp người mình quý mến, khuôn mặt thường cười và ánh mắt sáng.",
    },
    {
        "content_id": "cv-story-l4-angry-1",
        "game_id": GAME_CV_STORY,
        "level": 4,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ bị đổ oan làm vỡ đồ chơi dù mình không làm. Khuôn mặt bạn ấy có thể ra sao?",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Khi bị hiểu lầm, khuôn mặt có thể căng, nhíu mày và môi mím lại.",
    },
    {
        "content_id": "cv-story-l4-surprise-1",
        "game_id": GAME_CV_STORY,
        "level": 4,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Đèn tắt rồi mọi người bất ngờ hát chúc mừng sinh nhật bạn nhỏ. Khuôn mặt bạn ấy có thể thế nào?",
        "correct_answer": "surprise",
        "emotion": "surprise",
        "explanation": "Khi bất ngờ vui xảy ra, mắt thường mở to và lông mày nâng lên.",
    },
    {
        "content_id": "cv-story-l5-fear-1",
        "game_id": GAME_CV_STORY,
        "level": 5,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ nghe tiếng cửa đóng sầm trong căn phòng tối. Khuôn mặt bạn ấy có thể biểu hiện ra sao?",
        "correct_answer": "fear",
        "emotion": "fear",
        "explanation": "Khi gặp âm thanh mạnh trong bóng tối, khuôn mặt có thể căng và mắt mở to.",
    },
    {
        "content_id": "cv-story-l5-disgust-1",
        "game_id": GAME_CV_STORY,
        "level": 5,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ mở hộp cơm để quên lâu ngày và ngửi thấy mùi rất khó chịu. Khuôn mặt có thể thế nào?",
        "correct_answer": "disgust",
        "emotion": "disgust",
        "explanation": "Khi gặp mùi khó chịu, khuôn mặt thường nhăn mũi và hơi quay đi.",
    },
    {
        "content_id": "cv-story-l5-sad-1",
        "game_id": GAME_CV_STORY,
        "level": 5,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ tập rất lâu nhưng vẫn chưa làm được bài. Bạn ấy cúi đầu nhìn vở. Khuôn mặt có thể ra sao?",
        "correct_answer": "sad",
        "emotion": "sad",
        "explanation": "Khi thất vọng, khuôn mặt có thể trầm xuống và ánh mắt buồn.",
    },
    {
        "content_id": "cv-story-l5-angry-1",
        "game_id": GAME_CV_STORY,
        "level": 5,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ đã nói dừng lại nhưng bạn khác vẫn tiếp tục trêu. Khuôn mặt bạn ấy có thể thế nào?",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Khi ranh giới bị phớt lờ, khuôn mặt có thể nghiêm và lông mày nhíu lại.",
    },
    {
        "content_id": "cv-story-l5-surprise-1",
        "game_id": GAME_CV_STORY,
        "level": 5,
        "content_type": "scenario",
        "media_path": None,
        "question_text": "Bạn nhỏ tưởng hộp rỗng nhưng mở ra lại thấy một chú mèo bông bên trong. Khuôn mặt bạn ấy sẽ ra sao?",
        "correct_answer": "surprise",
        "emotion": "surprise",
        "explanation": "Khi kết quả khác hẳn dự đoán, khuôn mặt có thể mở to mắt và miệng hơi há.",
    },
]


GAME_CONTENT = [
    {
        "content_id": "recognize-happy-1",
        "game_id": GAME_RECOGNIZE_EMOTION,
        "level": 1,
        "content_type": "image",
        "media_path": "/fe/assets/images/happy/happy_1.jpg",
        "question_text": "Bạn nhỏ trong ảnh đang cảm thấy thế nào?",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Nụ cười và ánh mắt sáng gợi ý cảm xúc vui.",
    },
    {
        "content_id": "recognize-sad-1",
        "game_id": GAME_RECOGNIZE_EMOTION,
        "level": 1,
        "content_type": "image",
        "media_path": "/fe/assets/images/sad/sad_1.jpg",
        "question_text": "Bạn nhỏ trong ảnh đang cảm thấy thế nào?",
        "correct_answer": "sad",
        "emotion": "sad",
        "explanation": "Nét mặt trầm và mắt nhìn xuống gợi ý cảm xúc buồn.",
    },
    {
        "content_id": "recognize-angry-2",
        "game_id": GAME_RECOGNIZE_EMOTION,
        "level": 2,
        "content_type": "image",
        "media_path": "/fe/assets/images/angry/angry_1.jpg",
        "question_text": "Khuôn mặt này thể hiện cảm xúc nào?",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Lông mày chau lại thường là dấu hiệu tức giận.",
    },
    {
        "content_id": "recognize-surprise-2",
        "game_id": GAME_RECOGNIZE_EMOTION,
        "level": 2,
        "content_type": "image",
        "media_path": "/fe/assets/images/surprise/surprise_1.jpg",
        "question_text": "Khuôn mặt này thể hiện cảm xúc nào?",
        "correct_answer": "surprise",
        "emotion": "surprise",
        "explanation": "Mắt và miệng mở to gợi ý ngạc nhiên.",
    },
    {
        "content_id": "match-happy-1",
        "game_id": GAME_EMOTION_MATCH,
        "level": 1,
        "content_type": "text",
        "media_path": None,
        "question_text": "Bé được tặng món quà yêu thích. Cảm xúc nào phù hợp?",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Được tặng quà thường làm mình vui.",
    },
    {
        "content_id": "match-angry-2",
        "game_id": GAME_EMOTION_MATCH,
        "level": 2,
        "content_type": "text",
        "media_path": None,
        "question_text": "Bạn giật đồ chơi khỏi tay bé. Cảm xúc nào có thể xuất hiện?",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Bị giật đồ bất ngờ có thể làm mình tức giận.",
    },
    {
        "content_id": "detective-fear-3",
        "game_id": GAME_DETECTIVE,
        "level": 3,
        "content_type": "story",
        "media_path": None,
        "question_text": "Minh bám chặt tay mẹ khi thấy chó lớn. Cảm xúc nào đang ẩn giấu?",
        "correct_answer": "fear",
        "emotion": "fear",
        "explanation": "Bám chặt người lớn khi gặp điều lạ có thể là sợ hãi.",
    },
    {
        "content_id": "cv-story-happy-1",
        "game_id": GAME_CV_STORY,
        "level": 1,
        "content_type": "scenario",
        "media_path": "/fe/assets/images/happy/happy_1.jpg",
        "question_text": "Nhân vật vừa nhận được lời khen. Hãy thể hiện khuôn mặt vui.",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Hãy mỉm cười và mở mắt tự nhiên.",
    },
    {
        "content_id": "cv-story-sad-1",
        "game_id": GAME_CV_STORY,
        "level": 1,
        "content_type": "scenario",
        "media_path": "/fe/assets/images/sad/sad_1.jpg",
        "question_text": "Nhân vật làm rơi kem xuống đất. Hãy thể hiện khuôn mặt buồn.",
        "correct_answer": "sad",
        "emotion": "sad",
        "explanation": "Hãy hạ miệng nhẹ và nhìn xuống.",
    },
    {
        "content_id": "cv-story-angry-2",
        "game_id": GAME_CV_STORY,
        "level": 2,
        "content_type": "scenario",
        "media_path": "/fe/assets/images/angry/angry_1.jpg",
        "question_text": "Nhân vật bị lấy mất đồ chơi. Hãy thể hiện khuôn mặt tức giận.",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Hãy chau lông mày và giữ miệng nghiêm.",
    },
    {
        "content_id": "cv-request-happy-1",
        "game_id": GAME_CV_REQUEST,
        "level": 1,
        "content_type": "request",
        "media_path": None,
        "question_text": "Hãy mỉm cười thật tươi và giữ biểu cảm vui vẻ trong vài giây.",
        "correct_answer": "happy",
        "emotion": "happy",
        "explanation": "Gợi ý: mỉm cười, mắt hơi híp lại và thả lỏng khuôn mặt.",
    },
    {
        "content_id": "cv-request-sad-1",
        "game_id": GAME_CV_REQUEST,
        "level": 1,
        "content_type": "request",
        "media_path": None,
        "question_text": "Hãy thể hiện khuôn mặt buồn bã và giữ biểu cảm trong vài giây.",
        "correct_answer": "sad",
        "emotion": "sad",
        "explanation": "Gợi ý: hạ khóe miệng, ánh mắt buồn và nhìn nhẹ xuống.",
    },
    {
        "content_id": "cv-request-angry-1",
        "game_id": GAME_CV_REQUEST,
        "level": 1,
        "content_type": "request",
        "media_path": None,
        "question_text": "Hãy thể hiện khuôn mặt tức giận một cách an toàn và giữ biểu cảm.",
        "correct_answer": "angry",
        "emotion": "angry",
        "explanation": "Gợi ý: nhíu mày, mím môi nhẹ và nhìn nghiêm.",
    },
    {
        "content_id": "cv-request-fear-1",
        "game_id": GAME_CV_REQUEST,
        "level": 1,
        "content_type": "request",
        "media_path": None,
        "question_text": "Hãy thể hiện khuôn mặt sợ hãi như khi nghe một tiếng động lớn.",
        "correct_answer": "fear",
        "emotion": "fear",
        "explanation": "Gợi ý: mở to mắt, hơi lùi mặt lại và giữ biểu cảm.",
    },
    {
        "content_id": "cv-request-surprise-1",
        "game_id": GAME_CV_REQUEST,
        "level": 1,
        "content_type": "request",
        "media_path": None,
        "question_text": "Hãy làm khuôn mặt ngạc nhiên như vừa nhìn thấy một món quà bất ngờ.",
        "correct_answer": "surprise",
        "emotion": "surprise",
        "explanation": "Gợi ý: mở to mắt, há miệng nhẹ và nâng lông mày.",
    },
    {
        "content_id": "cv-request-disgust-1",
        "game_id": GAME_CV_REQUEST,
        "level": 1,
        "content_type": "request",
        "media_path": None,
        "question_text": "Hãy thể hiện khuôn mặt ghê tởm như khi ngửi thấy mùi khó chịu.",
        "correct_answer": "disgust",
        "emotion": "disgust",
        "explanation": "Gợi ý: nhăn mũi, hơi cau mày và quay mặt nhẹ.",
    },
]


OBSOLETE_GAME_CONTENT_IDS = [
    "cv-request-surprise-3",
]


def _upsert(db: Session, model: type, key_name: str, rows: list[dict]) -> None:
    for row in rows:
        instance = db.get(model, row[key_name])
        if instance is None:
            db.add(model(**row))
        else:
            for key, value in row.items():
                setattr(instance, key, value)


def seed_static_content(db: Session) -> None:
    if OBSOLETE_GAME_CONTENT_IDS:
        db.query(GameContent).filter(GameContent.content_id.in_(OBSOLETE_GAME_CONTENT_IDS)).delete(synchronize_session=False)
    _upsert(db, Game, "game_id", GAMES)
    _upsert(db, EmotionConcept, "concept_id", EMOTION_CONCEPTS)
    _upsert(db, GameContent, "content_id", GAME_CONTENT + CV_STORY_CONTENT)
    db.commit()
